### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by experienceadvertising** [bernskioldmedia/ilmenite-olark#1]
I don't see a settings after I installed the plugin in wordpress where is it?

**Comment by ErikBernskiold** [comment]
The plugin adds a settings page under the "Settings" menu.

**Comment by experienceadvertising** [comment]
done thanks

Evan Weber
CEO,Experience Advertising, Inc.
954-662-8010
evan@experienceadvertising.com
http://www.experienceadvertising.com
https://www.facebook.com/ExperienceAdvertising?fref=ts
https://www.linkedin.com/in/evanweber1
