### ISSUE TITLE
Olark stopped working

### ISSUE THREAD

**Issue by pmarcus21** [bernskioldmedia/ilmenite-olark#3]
Olark was working fine, but suddenly stopped working on our website: www.palmhealthcare.com
Not sure how to get it working again.

**Comment by ErikBernskiold** [comment]
Hi there,
Did you do any other changes to your website? Added a plugin? Enabled caching, or something similar?

**Comment by pmarcus21** [comment]
Yes I did add a plugin..Crelly slider and also cached. Would I need to reinstall your plugin?

Thanks for your help!

Best Regards,

Patty Marcus
Media Manager

Palm Healthcare Company, Inc.
1177 George Bush Blvd
Delray Beach, FL 33483

561-921-6126 Office
561-921-6181 Fax
http://palmhealthcarefamily.com<http://palmhealthcarefamily.com/help>

Feed Your Passion, Starve Your Fear!
[cid:6F83FAF5-2B51-4B51-A80F-FE8A1A4FA201]

Confidentiality Notice: This e-mail, and any attachments, are intended only for the individual or company to which it is addressed and may contain proprietary information which is intended only for dissemination to its intended recipients. Further, this e-mail may also contain Protected Health Information and related materials whose usage & disclosure is further governed by HIPAA and other federal regulations. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying, distribution, or the taking of any action in reliance on the information contained herein is strictly prohibited. If you have received this e-mail and are not the intended recipient, you are instructed to notify the sender by reply e-mail and destroy all copies of the original message.
Please consider the environment before printing this e-mail.

**Comment by pmarcus21** [comment]
Never mind, it is working now. Thanks anyways for getting back to me.

Best Regards,

Patty Marcus
Media Manager

Palm Healthcare Company, Inc.
1177 George Bush Blvd
Delray Beach, FL 33483

561-921-6126 Office
561-921-6181 Fax
http://palmhealthcarefamily.com<http://palmhealthcarefamily.com/help>

Feed Your Passion, Starve Your Fear!
[cid:6F83FAF5-2B51-4B51-A80F-FE8A1A4FA201]

Confidentiality Notice: This e-mail, and any attachments, are intended only for the individual or company to which it is addressed and may contain proprietary information which is intended only for dissemination to its intended recipients. Further, this e-mail may also contain Protected Health Information and related materials whose usage & disclosure is further governed by HIPAA and other federal regulations. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying, distribution, or the taking of any action in reliance on the information contained herein is strictly prohibited. If you have received this e-mail and are not the intended recipient, you are instructed to notify the sender by reply e-mail and destroy all copies of the original message.
Please consider the environment before printing this e-mail.
